### ISSUE TITLE
Container dies when using custom bpm-platform.xml file

### ISSUE THREAD

**Issue by mraslam** [camunda/docker-camunda-bpm-platform#188]
I followed the instructions as per doc to add custom file but I get an error. 

docker run -d --name camunda -p 8080:8080 \
           -v $PWD/bpm-platform.xml:/camunda/conf/bpm-platform.xml \
           camunda/camunda-bpm-platform:7.15.0

Error:
/lib/jvm/java-11-openjdk/lib:/usr/lib/jvm/java-11-openjdk/../lib:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib]
29-Jul-2021 14:57:09.527 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
29-Jul-2021 14:57:09.571 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [1006] milliseconds
29-Jul-2021 14:57:09.894 INFO [main] org.camunda.commons.logging.BaseLogger.logInfo ENGINE-08046 Found Camunda Platform configuration in CATALINA_BASE/CATALINA_HOME conf directory [/camunda/conf/bpm-platform.xml] at 'file:/camunda/conf/bpm-platform.xml'
29-Jul-2021 14:57:10.053 SEVERE [main] org.apache.catalina.startup.Catalina.start The required Server component failed to start so Tomcat is unable to start.
        org.apache.catalina.LifecycleException: Failed to start component [StandardServer[8005]]
                at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
                at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
        Caused by: org.camunda.bpm.engine.ProcessEngineException: ENGINE-08043 Exception while performing 'deploy BPM platform' => 'Start process engine default': ENGINE-09017 Cannot load class 'org.camunda.cawemo.plugin.CawemoEnginePlugin': org.camunda.cawemo.plugin.CawemoEnginePlugin

**Comment by koevskinikola** [comment]
Hi @mraslam,

It looks to me like you forgot to provide the Cawemo process engine plugin, or you placed it in the wrong location. So the engine can't find the `org.camunda.cawemo.plugin.CawemoEnginePlugin` that you define in your `bpm-platform.xml` file.

I would recommend to open a help request topic on the [Camunda forum](https://forum.camunda.org/) or [opening a help request support ticket](https://docs.camunda.org/enterprise/support/#how-to-create-a-support-issue) if you are an enterprise customer.

I am closing this issue, as it is a help request. We will soon disable the GitHub issues on this repository. In the future, please use our [JIRA issue tracker](https://jira.camunda.com/projects/CAM/issues/CAM-2099?filter=allopenissues).

Best,
Nikola
